version: '2'
services:
  job-db:
    image: postgres
    container_name: postgres1
    ports:
      - '5461:5432'
    environment:
      - POSTGRES_USER=proemploi
      - POSTGRES_PASSWORD=proemploi
      - POSTGRES_DB=proemploidb

