spring:
  datasource:
    url: jdbc:postgresql://localhost:5461/proemploidb
    username: proemploi
    password: proemploi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
